import React from 'react'
import { Anchor, Waves, Wind, Eye, CloudLightning, Activity, AlertTriangle, CheckCircle2, ShieldAlert } from 'lucide-react'
import { useGlobal, VESSEL_PROFILES } from '../../context/GlobalContext'

export default function VesselLimitGauges({ safetyData = {} }) {
  const { vessel, setVessel, t } = useGlobal()
  const activeProfile = VESSEL_PROFILES[vessel] || VESSEL_PROFILES.fishing_trawler

  const conditions = safetyData.conditions || {}
  const thresholds = safetyData.thresholds || activeProfile.limits || {
    wave_m: 1.5,
    wind_kmh: 30,
    gusts_kmh: 45,
    swell_m: 1.5,
    visibility_m: 2000,
    cape_j_per_kg: 1500,
  }

  // Parameter evaluations
  const waveVal = conditions.wave_m ?? 0.9
  const waveLimit = thresholds.wave_m || activeProfile.limits?.wave || 1.5
  const wavePct = Math.min(100, Math.round((waveVal / waveLimit) * 100))

  const swellVal = conditions.swell_m ?? 0.7
  const swellLimit = thresholds.swell_m || 1.5
  const swellPct = Math.min(100, Math.round((swellVal / swellLimit) * 100))

  const windVal = conditions.wind_kmh ?? 11.2
  const windLimit = thresholds.wind_kmh || activeProfile.limits?.wind || 30
  const windPct = Math.min(100, Math.round((windVal / windLimit) * 100))

  const gustsVal = conditions.gusts_kmh ?? 27.0
  const gustsLimit = thresholds.gusts_kmh || 45
  const gustsPct = Math.min(100, Math.round((gustsVal / gustsLimit) * 100))

  const visVal = conditions.visibility_m ? conditions.visibility_m / 1000 : 19.3
  const visMinLimit = (thresholds.visibility_m || 2000) / 1000
  const visStatus = visVal >= visMinLimit ? 'SAFE' : 'DANGER'

  const capeVal = conditions.cape_j_per_kg != null
    ? Math.round(conditions.cape_j_per_kg)
    : (safetyData.warnings?.some(w => w.includes('CAPE') || w.includes('lightning')) ? 2600 : 850)
  const capeLimit = thresholds.cape_j_per_kg || 1500
  const capePct = Math.min(100, Math.round((capeVal / capeLimit) * 100))

  const gaugeList = [
    {
      title: 'Significant Wave Height',
      icon: Waves,
      val: `${waveVal.toFixed(1)} m`,
      limit: `${t('Limit')}: ${waveLimit} m`,
      pct: wavePct,
      status: waveVal > waveLimit ? 'DANGER' : waveVal > waveLimit * 0.8 ? 'CAUTION' : 'SAFE',
      desc: 'Sea surface crest-to-trough average of highest one-third waves',
    },
    {
      title: 'Deep Ocean Swell',
      icon: Activity,
      val: `${swellVal.toFixed(1)} m`,
      limit: `${t('Limit')}: ${swellLimit} m`,
      pct: swellPct,
      status: swellVal > swellLimit ? 'DANGER' : swellVal > swellLimit * 0.8 ? 'CAUTION' : 'SAFE',
      desc: 'Long-period swell generated by distant maritime low pressure',
    },
    {
      title: 'Sustained Wind Speed',
      icon: Wind,
      val: `${windVal.toFixed(1)} km/h`,
      limit: `${t('Limit')}: ${windLimit} km/h`,
      pct: windPct,
      status: windVal > windLimit ? 'DANGER' : windVal > windLimit * 0.8 ? 'CAUTION' : 'SAFE',
      desc: '10-minute average wind velocity at 10m above sea level',
    },
    {
      title: 'Peak Wind Gusts',
      icon: Wind,
      val: `${gustsVal.toFixed(0)} km/h`,
      limit: `${t('Limit')}: ${gustsLimit} km/h`,
      pct: gustsPct,
      status: gustsVal > gustsLimit ? 'DANGER' : gustsVal > gustsLimit * 0.8 ? 'CAUTION' : 'SAFE',
      desc: 'Sudden high-speed turbulent bursts dangerous for smaller craft',
    },
    {
      title: 'Convective Energy (CAPE)',
      icon: CloudLightning,
      val: `${capeVal} J/kg`,
      limit: `${t('Limit')}: ${capeLimit} J/kg`,
      pct: capePct,
      status: capeVal > capeLimit ? 'DANGER' : capeVal > capeLimit * 0.7 ? 'CAUTION' : 'SAFE',
      desc: 'Convective Available Potential Energy for severe thunderstorm build-up',
    },
    {
      title: 'Atmospheric Visibility',
      icon: Eye,
      val: `${visVal.toFixed(1)} km`,
      limit: `${t('Min Required')}: ${visMinLimit.toFixed(1)} km`,
      pct: Math.min(100, Math.round((visVal / 20) * 100)),
      status: visStatus,
      desc: 'Daylight horizontal line of sight across sea horizon',
    },
  ]

  const getStatusBadge = (status) => {
    if (status === 'DANGER') {
      return (
        <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-red-100 text-dangerRed flex items-center gap-1">
          <ShieldAlert size={11} /> {t('Exceeded')}
        </span>
      )
    }
    if (status === 'CAUTION') {
      return (
        <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-amber-100 text-amber-800 flex items-center gap-1">
          <AlertTriangle size={11} /> {t('Elevated')}
        </span>
      )
    }
    return (
      <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-emerald-100 text-safeGreen flex items-center gap-1">
        <CheckCircle2 size={11} /> {t('Within Limit')}
      </span>
    )
  }

  const getBarColor = (status) => {
    if (status === 'DANGER') return 'bg-dangerRed'
    if (status === 'CAUTION') return 'bg-warnAmber'
    return 'bg-safeGreen'
  }

  return (
    <div className="p-6 rounded-3xl bg-white border border-borderLight shadow-sm space-y-6">
      {/* Header & Vessel Profile Switcher */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-borderLight">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-oceanBlue/10 text-oceanBlue flex items-center justify-center">
              <Anchor size={17} />
            </div>
            <h3 className="text-sm md:text-base font-bold text-navy">
              {t('Vessel Operating Limits vs Live Sea Conditions')}
            </h3>
          </div>
          <p className="text-xs text-textMuted mt-0.5">
            {t('Real-time threshold evaluation calibrated to your vessel class')}
          </p>
        </div>

        {/* Vessel profile selection chips */}
        <div className="flex items-center gap-1.5 flex-wrap">
          {Object.entries(VESSEL_PROFILES).map(([key, prof]) => {
            const isSelected = key === vessel
            return (
              <button
                key={key}
                onClick={() => setVessel(key)}
                className={`px-3 py-1.5 rounded-2xl text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 border ${
                  isSelected
                    ? 'bg-navy text-white border-navy shadow-xs'
                    : 'bg-surface hover:bg-surfaceMid text-textSecond border-borderLight'
                }`}
              >
                <span>{prof.icon}</span>
                <span>{t(prof.label)}</span>
              </button>
            )
          })}
        </div>
      </div>

      {/* 6 Parameter Threshold Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {gaugeList.map((g, idx) => {
          const Icon = g.icon
          return (
            <div
              key={idx}
              className={`p-4 rounded-2xl border transition-all ${
                g.status === 'DANGER'
                  ? 'bg-red-50/50 border-red-200 shadow-2xs'
                  : g.status === 'CAUTION'
                  ? 'bg-amber-50/40 border-amber-200 shadow-2xs'
                  : 'bg-surface/50 border-borderLight'
              }`}
            >
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-xl bg-white shadow-2xs text-navy border border-borderLight">
                    <Icon size={15} />
                  </div>
                  <span className="text-xs font-bold text-navy">{t(g.title)}</span>
                </div>
                {getStatusBadge(g.status)}
              </div>

              {/* Values */}
              <div className="flex items-baseline justify-between mt-3">
                <div className="text-xl font-black font-mono text-navy">{g.val}</div>
                <div className="text-[11px] font-semibold text-textMuted font-mono">{g.limit}</div>
              </div>

              {/* Progress Bar */}
              <div className="w-full bg-borderLight/80 h-2 rounded-full mt-2 overflow-hidden">
                <div
                  className={`h-full transition-all duration-500 rounded-full ${getBarColor(g.status)}`}
                  style={{ width: `${g.pct}%` }}
                />
              </div>

              <p className="text-[10px] text-textMuted mt-2 leading-relaxed">
                {t(g.desc)}
              </p>
            </div>
          )
        })}
      </div>
    </div>
  )
}
